### ISSUE TITLE
Feature request: Java 11 based image

### ISSUE THREAD

**Issue by dalbani** [bitnami/bitnami-docker-solr#29]
The Bitnami Solr image currently uses Java 8, which has been introduced in 2014(!).
Do you plan to provide a Java 11 based image?
With the next LTS (Java 17) about to be released in a couple of months, I think it's time to use a more modern JVM.

By the way, why is this image based on `bitnami/minideb` and not `bitnami/java`??

Thanks for all your hard work maintaining this image in any case! 👍

**Comment by miguelaeh** [comment]
Hi @dalbani ,

We use Java 8 mainly because it is the lower version compatible checking the Solr docs. The next Solr version will probably require Java 11, so we will probably update it then.

> By the way, why is this image based on bitnami/minideb and not bitnami/java??

Minideb is our base image for all the containers. After all, the java image is also based on minideb so in the end, it will be the same.
We cannot base the image on the java image due to other internal requirements.
